### ISSUE TITLE
你好 我想问一下新版本v2.0.0.0，”追更任务范围“和”可选独占模式功能控制“不选择是默认全选吗？

### ISSUE THREAD

**Issue by beatter789** [sjtuross/StrmExtract#52]
你好 我想问一下新版本v2.0.0.0，”追更任务范围“和”可选独占模式功能控制“不选择是默认全选吗？

**Comment by sjtuross** [comment]
留空都不是全选

追更任务范围如果留空会被自动设成默认值`媒体信息提取`，否则没有意义

`可选独占模式功能控制`用在一些需求冲突的场景，具体看下Wiki的后半部分 https://github.com/sjtuross/StrmAssistant/wiki/独占媒体信息提取-(Exclusive-Extract)
